config/routes.rb
Rails.application.routes.draw do
  resources :scans
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/scan.rb
class Scan < ApplicationRecord
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/scans_controller.rb
class ScansController < ApplicationController
  before_action :set_scan, only: %i[ show edit update destroy ]

  # GET /scans or /scans.json
  def index
    @scans = Scan.all
  end

  # GET /scans/1 or /scans/1.json
  def show
  end

  # GET /scans/new
  def new
    @scan = Scan.new
  end

  # GET /scans/1/edit
  def edit
  end

  # POST /scans or /scans.json
  def create
    @scan = Scan.new(video_params)

    respond_to do |format|
      if @scan.save
        format.html { redirect_to scan_url(@scan), notice: "Scan was successfully created." }
        format.json { render :show, status: :created, location: @scan }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @scan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scans/1 or /scans/1.json
  def update
    respond_to do |format|
      if @scan.update(video_params)
        format.html { redirect_to scan_url(@scan), notice: "Scan was successfully updated." }
        format.json { render :show, status: :ok, location: @scan }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @scan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scans/1 or /scans/1.json
  def destroy
    @scan.destroy!

    respond_to do |format|
      format.html { redirect_to scans_url, notice: "Scan was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scan
      @scan = Scan.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def scan_params
      params.require(:scan).permit(:title, :photo)
    end

    def video_params
      params.require(:scan).permit(:title, :photo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyScanApp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/scans/_form.html.erb
<%= simple_form_for(@scan) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :photo, as: :file %>
  </div>
  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/scans/_scan.html.erb
<div id="<%= dom_id scan %>">
  <p>
    <strong>Title:</strong>
    <%= scan.title %>
  </p>

</div>

app/views/scans/edit.html.erb
<h1>Editing scan</h1>

<%= render "form", scan: @scan %>

<br>

<div>
  <%= link_to "Show this scan", @scan %> |
  <%= link_to "Back to scans", scans_path %>
</div>

app/views/scans/index.html.erb
<div class="container">
  <div class="col-8 mt-5 mx-auto">
    <p style="color: green"><%= notice %></p>
    <h1>Scans</h1>

    <div class="row mt-5">
      <% @scans.each do |scan| %>
        <div class="col-6">
        <table>
          <tr>
            <td><%= scan.title %></td>
            <% if scan.photo.attached? %>
              <td class="image"><%= cl_image_tag scan.photo.key , alt: "tag scan", style: "width: 100px" %></td>
            <% end %>
          </tr>
          <tr>
            <td><%= link_to 'Show', scan %></td>
            <td><%= link_to 'Edit', edit_scan_path(scan) %></td>
            <td><%= link_to 'Destroy', scan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
          </table>
        </div>
      <% end %>
    </div>
    <div class="row mt-5">
    <%= link_to "New scan", new_scan_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/scans/new.html.erb
<div class="container">
  <div class="row justify-content-center text-center m-5">
    <div class="col-8">
      <h1 class="mb-3">Take a Scan!</h1>
      <%#= render 'form', scan: @scan %>
      <div class="scan-container" data-controller="scan">
        <video class="scan-video" data-scan-target="video">
          Video stream not available.
        </video>
        <button class="scan-startbutton" data-action="click->scan#takePicture" data-scan-target="startbutton">📸</button>
        <!-- Optional: Element to display the scan image -->
        <img class="scan-photo" style="display:none;" data-scan-target="photo">
      </div>

      <%= link_to 'Back', scans_path, class: "btn btn-outline-primary" %>
    </div>
  </div>
</div>

app/views/scans/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @scan %>

<div>
  <%= link_to "Edit this scan", edit_scan_path(@scan) %> |
  <%= link_to "Back to scans", scans_path %>

  <%= button_to "Destroy this scan", @scan, method: :delete %>
</div>